name: BitLoteria_Persistente

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  search:
    runs-on: ubuntu-latest
    permissions:
      contents: write # ESSENCIAL: Permite salvar no reposit√≥rio
    
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Libs
        run: npm install secp256k1

      - name: Executar Busca
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        timeout-minutes: 345
        run: node fast-loteria.js || echo "Tempo esgotado, salvando..."

      - name: Commit e Push do Progresso
        if: always() # Salva mesmo se o script falhar ou parar por tempo
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          git add last_key.txt
          git commit -m "Update progresso: $(cat last_key.txt)" || exit 0
          git push
